import subprocess,time,json,pathlib
root=pathlib.Path('/workspace/shared/box-url-mutant');out=pathlib.Path('/workspace/shared/box-url-evidence');rows=[]
mutants=[('literal-plus','rust/crates/bellobox-core/src/url_editor.rs','value: decode(v.unwrap_or(""))?,','value: decode(v.unwrap_or("")).map(|s|s.replace(\'+\', " "))?,','cargo test -p bellobox-core --lib url_editor::tests::ordered_flags_blank_plus_and_components --locked --offline'),('flag-equals','rust/crates/bellobox-core/src/url_editor.rs','if p.has_value {','if true {','cargo test -p bellobox-core --lib url_editor::tests::ordered_flags_blank_plus_and_components --locked --offline'),('stale-copy-token','rust/crates/bellobox-app/src/url_ui.rs','&& self.tokens(cx) == self.built_tokens','&& true','cargo test -p bellobox-app url_ui::tests::full_url_requires_build_and_blocks_same_callback_stale_copy --locked --offline'),('reject-latch','rust/crates/bellobox-app/src/url_ui.rs','self.rejected\n            || self.tokens(cx).iter().any(|t| !t.2)','false\n            || self.tokens(cx).iter().any(|t| !t.2)','cargo test -p bellobox-app url_ui::tests::source_typing_is_explicit_inspection_and_rejected_paste_latches --locked --offline')]
mutants.append(('page-aba','rust/crates/bellobox-app/src/url_ui.rs','if self.built.as_ref().is_some_and(|built| built != &d) {','if false {','cargo test -p bellobox-app url_ui::tests::page_remount_cannot_aba_a_built_token_before_queued_notifications --locked --offline'))
for name,path,old,new,command in mutants:
 p=root/path;original=p.read_text();assert old in original,(name,old);p.write_text(original.replace(old,new,1));t=time.monotonic()
 try:
  with (out/('mutant-'+name+'.log')).open('w') as log:r=subprocess.run(['bash','-c','source /workspace/shared/build-recovery/env.sh; source /workspace/shared/build-recovery/gpui-env.sh; cargo clean -p bellobox-core -p bellobox-app; '+command],cwd=root/'rust',stdout=log,stderr=subprocess.STDOUT)
 finally:p.write_text(original)
 text=(out/('mutant-'+name+'.log')).read_text();rows.append(dict(name=name,seconds=round(time.monotonic()-t,3),exit_code=r.returncode,killed=r.returncode!=0 and 'test result: FAILED' in text));(out/'mutants.json').write_text(json.dumps(rows,indent=2));print(rows[-1],flush=True)
