import subprocess,time,json,pathlib,datetime

root='/workspace/shared/box-url-workflow/rust';out=pathlib.Path('/workspace/shared/box-url-evidence'); rows=[]
commands=[('fmt','cargo fmt --all -- --check'),('core-default','cargo test -p bellobox-core --locked --offline'),('core-minimal','cargo test -p bellobox-core --no-default-features --locked --offline'),('app-default','cargo test -p bellobox-app --locked --offline'),('app-minimal','cargo test -p bellobox-app --no-default-features --locked --offline'),('app-recording','cargo test -p bellobox-app --features recording-fixtures --locked --offline'),('editor-core','cargo test -p bello-workbench --locked --offline'),('editor-ui','cargo test -p bello-workbench-ui --locked --offline'),('strict','cargo clippy -p bellobox-app -p bellobox-core -p bello-workbench-ui -p bello-workbench --all-targets --locked --offline -- -D warnings'),('strict-recording','cargo clippy -p bellobox-app --features recording-fixtures --all-targets --locked --offline -- -D warnings'),('clean-app','cargo clean -p bellobox-app'),('ordinary-build','cargo build -p bellobox-app --locked --offline')]
commands=[(n,c) for n,c in commands if n in ['fmt','app-default','app-minimal','app-recording','strict','strict-recording','clean-app','ordinary-build']]
out=out/'support-closure';out.mkdir(exist_ok=True)
for name,cmd in commands:
 t=time.monotonic();start=datetime.datetime.now(datetime.timezone.utc).isoformat();r=subprocess.run(['bash','-c','source /workspace/shared/build-recovery/env.sh; source /workspace/shared/build-recovery/gpui-env.sh; '+cmd],cwd=root,stdout=(out/(name+'.log')).open('w'),stderr=subprocess.STDOUT);rows.append(dict(name=name,command=cmd,started=start,seconds=round(time.monotonic()-t,3),exit_code=r.returncode));(out/'gate-timings.json').write_text(json.dumps(rows,indent=2));print(rows[-1],flush=True)
 if r.returncode: break
