use super::{pixel_rect, plain_text, recognized_text, tile_bands, Rect, Region};

/// Generated by Swift Box's own layout code (e43b1c4 `OCRTileSegmenter`,
/// `OCRBoundingBoxConverter`, `OCRResultFormatter`) on fixed-seed region sets;
/// harness in rust/docs/validation/ocr-swift-oracle-2026-10-10.
const ORACLE: &str = include_str!("../../tests/data/ocr_layout_swift_oracle.json");

fn region(value: &serde_json::Value) -> Region {
    Region {
        text: value["text"].as_str().unwrap().to_owned(),
        rect: value.get("rect").map(|rect| {
            let n = |i: usize| rect[i].as_f64().unwrap();
            Rect::new(n(0), n(1), n(2), n(3))
        }),
    }
}

#[test]
fn reading_order_overlap_removal_and_text_match_swift() {
    let oracle: serde_json::Value = serde_json::from_str(ORACLE).unwrap();
    let cases = oracle["cases"].as_array().unwrap();
    assert_eq!(cases.len(), 80);
    for (number, case) in cases.iter().enumerate() {
        let regions: Vec<Region> = case["regions"]
            .as_array()
            .unwrap()
            .iter()
            .map(region)
            .collect();
        let pick = |key: &str| -> Vec<Region> {
            case[key]
                .as_array()
                .unwrap()
                .iter()
                .map(|index| regions[index.as_u64().unwrap() as usize].clone())
                .collect()
        };
        assert_eq!(
            super::reading_order(&regions),
            pick("order"),
            "order, case {number}"
        );
        assert_eq!(
            super::deduplicate(&regions),
            pick("dedup"),
            "dedup, case {number}"
        );
        assert_eq!(
            plain_text(&super::deduplicate(&regions)),
            case["plain"].as_str().unwrap(),
            "text, case {number}"
        );
    }
}

#[test]
fn tall_images_are_read_in_the_same_bands_as_swift() {
    let oracle: serde_json::Value = serde_json::from_str(ORACLE).unwrap();
    for plan in oracle["plans"].as_array().unwrap() {
        let height = plan["height"].as_u64().unwrap();
        let expected: Vec<(u64, u64)> = plan["bands"]
            .as_array()
            .unwrap()
            .iter()
            .map(|band| (band[0].as_u64().unwrap(), band[1].as_u64().unwrap()))
            .collect();
        assert_eq!(tile_bands(height), expected, "height {height}");
    }
}

#[test]
fn vision_boxes_flip_to_top_left_pixels_and_blank_results_are_no_text() {
    // Vision: normalized, bottom-left origin.
    let rect = pixel_rect(Rect::new(0.25, 0.5, 0.5, 0.25), 400.0, 200.0);
    assert_eq!(rect, Rect::new(100.0, 50.0, 200.0, 50.0));
    let line = |text: &str, y: f64| Region {
        text: text.into(),
        rect: Some(Rect::new(10.0, y, 100.0, 20.0)),
    };
    assert_eq!(recognized_text(&[]), None);
    assert_eq!(recognized_text(&[line(" \u{3000}\n", 0.0)]), None);
    // A gap of more than 1.35 line heights starts a paragraph.
    assert_eq!(
        recognized_text(&[line("b", 30.0), line(" a ", 0.0), line("c", 90.0)]).as_deref(),
        Some("a\nb\n\nc")
    );
    // The same line read twice in a band overlap is kept once.
    assert_eq!(
        recognized_text(&[line("a", 0.0), line("a", 2.0), line("b", 30.0)]).as_deref(),
        Some("a\nb")
    );
}

/// Apple Vision on generated images (rust/docs/validation/ocr-swift-oracle-2026-10-10
/// has the generator and the exact Swift-oracle comparison on this kind of input).
/// Vision's wording can differ between macOS versions, so this asserts layout.
#[cfg(target_os = "macos")]
#[test]
fn vision_text_comes_out_in_swift_reading_order_with_paragraph_breaks() {
    let fixture = |name: &str| {
        std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("tests/data/ocr")
            .join(name)
    };
    let platform = crate::Platform::new();
    let words = |line: &str| -> String {
        line.chars()
            .filter(|c| c.is_alphanumeric() || *c == ' ')
            .collect::<String>()
            .to_lowercase()
    };
    // Rows are read across both columns before the next row.
    let columns = platform
        .recognize_text(&fixture("columns.png"), None)
        .unwrap();
    let lines: Vec<String> = columns.lines().map(words).collect();
    let mut expected = Vec::new();
    for row in ["first", "second", "third", "fourth"] {
        expected.push(format!("left column {row} line"));
        expected.push(format!("right column {row} line"));
    }
    expected.push(String::new());
    expected.push("a footer spanning the page below both columns".into());
    assert_eq!(lines, expected, "{columns}");
    // Title, two paragraphs and a footer, separated by blank lines.
    let paragraphs = platform
        .recognize_text(&fixture("paragraphs.png"), None)
        .unwrap();
    let blocks: Vec<usize> = paragraphs
        .split("\n\n")
        .map(|block| block.lines().count())
        .collect();
    assert_eq!(blocks, [1, 3, 2, 1], "{paragraphs}");
    let blank = platform
        .recognize_text(&fixture("blank.png"), None)
        .unwrap_err();
    assert_eq!(blank.message, "No text was found in this screenshot.");
}
